// app/api/admin/data-subject-request/send/route.ts
//
// Sends a (possibly admin-edited) summary generated by
// data-subject-request/summary/route.ts to the data subject's own
// registered email — never a client-supplied address, to avoid ever
// routing someone's personal-data summary to the wrong inbox. Logs both a
// PDPA_SUMMARY_SENT audit_log entry (same pattern as the parent route's
// PDPA_ACCESS_REQUEST) and an email_notification_log row, for the same
// reason every other outbound email in this app is tracked.
import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import prisma from "@/lib/prisma";
import { getCorsHeaders, handleCorsOptions } from "@/lib/cors";
import { logEvent, extractAuditContext } from "@/lib/audit";
import { logEmailNotification } from "@/lib/notifications";
import { sendDsrSummaryEmail } from "@/lib/email";
import { isAuthorized } from "../route";
import { z } from "zod";

const bodySchema = z.object({
  user_id: z.coerce.number().int().positive(),
  // 10000 covers the "detailed" mode's per-category row listings (up to 8
  // categories x 10 rows each) as well as the shorter default summary.
  summary_text: z.string().trim().min(1).max(10000),
});

export async function OPTIONS(request: NextRequest) {
  const origin = request.headers.get("origin");
  const corsResponse = handleCorsOptions(origin);
  if (corsResponse) return corsResponse;
  return new NextResponse(null, { status: 204 });
}

export async function POST(request: NextRequest) {
  const origin = request.headers.get("origin");
  const corsHeaders = getCorsHeaders(origin);

  const session = await getServerSession(authOptions);
  if (!session || !(await isAuthorized(Number(session.user.id)))) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403, headers: corsHeaders });
  }

  const parsed = bodySchema.safeParse(await request.json().catch(() => ({})));
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Invalid request body", details: parsed.error.issues },
      { status: 400, headers: corsHeaders }
    );
  }
  const { user_id, summary_text } = parsed.data;

  const target = await prisma.users.findUnique({
    where: { user_id },
    select: { username: true, email: true, display_name: true },
  });
  if (!target) {
    return NextResponse.json({ error: "User not found" }, { status: 404, headers: corsHeaders });
  }

  let delivered = true;
  try {
    await sendDsrSummaryEmail({
      to: target.email,
      recipientName: target.display_name || target.username,
      summaryText: summary_text,
    });
  } catch (error) {
    delivered = false;
    console.error("Failed to send DSR summary email:", error);
  }

  await logEmailNotification({
    eventType: "dsr_summary_sent",
    recipientUserId: user_id,
    recipientEmail: target.email,
    isDelivered: delivered,
  });

  if (!delivered) {
    return NextResponse.json(
      { error: "Failed to send the email. Please try again." },
      { status: 502, headers: corsHeaders }
    );
  }

  const ctx = extractAuditContext(request);
  await logEvent({
    tableName: "users",
    recordId: user_id,
    action: "PDPA_SUMMARY_SENT",
    userId: Number(session.user.id),
    ipAddress: ctx.ipAddress,
    userAgent: ctx.userAgent,
    requestId: ctx.requestId,
    details: { ...ctx.details, target_user_id: user_id, target_username: target.username },
  });

  return NextResponse.json({ success: true }, { headers: corsHeaders });
}
