import { BrandRules, BrandKey } from '@/types/capex';

export const brandRulesMap: Record<BrandKey, BrandRules> = {
  'Yun Nam': {
    brand: 'Yun Nam',
    costTiers: [
      { threshold: 1200, ratePerSqft: 147, nextRatePerSqft: 114 },
      { threshold: 1400, ratePerSqft: 144, nextRatePerSqft: 108 },
      { threshold: 1600, ratePerSqft: 139, nextRatePerSqft: 102 },
      { threshold: 1800, ratePerSqft: 136, nextRatePerSqft: 90 },
      { threshold: 2000, ratePerSqft: 131, nextRatePerSqft: 84 },
      { threshold: 2200, ratePerSqft: 127, nextRatePerSqft: 78 },
      { threshold: 2400, ratePerSqft: 123, nextRatePerSqft: 72 },
      { threshold: 2600, ratePerSqft: 119, nextRatePerSqft: 60 },
      { threshold: 2800, ratePerSqft: 115, nextRatePerSqft: 54 },
      { threshold: 3000, ratePerSqft: 111, nextRatePerSqft: 48 },
    ],
    budgetAllocation: {
      renovation: 1.0,
      refurbishment1st: 0.08,
      refurbishment2nd: 0.16,
      refurbishment3rd: 0.7,
      rebranding: 0.15,
      reinstatement: 0.12,
    },
    hasBlueSpirit: false,
    hasMaleBed: false,
    hasMealPlan: false,
    capacityRules: {
      'Below 1300': {
        minCR: 2, maxCR: 3,
        minTR: 3, maxTR: 3,
        minOpenTR: 10, maxOpenTR: 12,
        minShampoo: 2, maxShampoo: 3,
        minTotalBeds: 13, maxTotalBeds: 15,
      },
      '1301 - 1500': {
        minCR: 2, maxCR: 3,
        minTR: 3, maxTR: 4,
        minOpenTR: 12, maxOpenTR: 14,
        minShampoo: 2, maxShampoo: 3,
        minTotalBeds: 15, maxTotalBeds: 16,
      },
      '1501 - 1700': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 14, maxOpenTR: 17,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 18, maxTotalBeds: 22,
      },
      '1701 - 1900': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 17, maxOpenTR: 22,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 21, maxTotalBeds: 27,
      },
      '1901 - 2100': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 19, maxOpenTR: 23,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 23, maxTotalBeds: 28,
      },
      '2101 - 2300': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 21, maxOpenTR: 24,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 25, maxTotalBeds: 29,
      },
      '2301 above': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 23, maxOpenTR: 25,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 27, maxTotalBeds: 30,
      },
    },
  },
  London: {
    brand: 'London',
    costTiers: [
      { threshold: 1200, ratePerSqft: 162, nextRatePerSqft: 127 },
      { threshold: 1400, ratePerSqft: 158, nextRatePerSqft: 121 },
      { threshold: 1600, ratePerSqft: 153, nextRatePerSqft: 115 },
      { threshold: 1800, ratePerSqft: 150, nextRatePerSqft: 104 },
      { threshold: 2000, ratePerSqft: 145, nextRatePerSqft: 98 },
      { threshold: 2200, ratePerSqft: 141, nextRatePerSqft: 92 },
      { threshold: 2400, ratePerSqft: 137, nextRatePerSqft: 86 },
      { threshold: 2600, ratePerSqft: 133, nextRatePerSqft: 75 },
      { threshold: 2800, ratePerSqft: 129, nextRatePerSqft: 69 },
      { threshold: 3000, ratePerSqft: 125, nextRatePerSqft: 63 },
    ],
    budgetAllocation: {
      renovation: 1.0,
      refurbishment1st: 0.08,
      refurbishment2nd: 0.16,
      refurbishment3rd: 0.7,
      rebranding: 0.15,
      reinstatement: 0.12,
    },
    hasBlueSpirit: true,
    hasMaleBed: false,
    hasMealPlan: false,
    capacityRules: {
      'Min 1400': {
        minCR: 2, maxCR: 3,
        minTR: 4, maxTR: 6,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 2, maxBlueSpirit: 3,
        minTotalBeds: 6, maxTotalBeds: 9,
      },
      '1401 - 1600': {
        minCR: 3, maxCR: 4,
        minTR: 5, maxTR: 7,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 2, maxBlueSpirit: 3,
        minTotalBeds: 7, maxTotalBeds: 10,
      },
      '1601 - 1800': {
        minCR: 3, maxCR: 4,
        minTR: 7, maxTR: 9,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 2, maxBlueSpirit: 4,
        minTotalBeds: 9, maxTotalBeds: 13,
      },
      '1801 - 2000': {
        minCR: 3, maxCR: 4,
        minTR: 9, maxTR: 11,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 2, maxBlueSpirit: 4,
        minTotalBeds: 11, maxTotalBeds: 15,
      },
      '2001 - 2200': {
        minCR: 3, maxCR: 4,
        minTR: 10, maxTR: 12,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 2, maxBlueSpirit: 4,
        minTotalBeds: 12, maxTotalBeds: 16,
      },
      '2201 - 2400': {
        minCR: 3, maxCR: 4,
        minTR: 12, maxTR: 14,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 2, maxBlueSpirit: 4,
        minTotalBeds: 14, maxTotalBeds: 16,
      },
      '2400 above': {
        minCR: 3, maxCR: 4,
        minTR: 14, maxTR: 16,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 2, maxBlueSpirit: 4,
        minTotalBeds: 16, maxTotalBeds: 20,
      },
    },
  },
  'New York': {
    brand: 'New York',
    costTiers: [
      { threshold: 1200, ratePerSqft: 131, nextRatePerSqft: 100 },
      { threshold: 1400, ratePerSqft: 128, nextRatePerSqft: 94 },
      { threshold: 1600, ratePerSqft: 123, nextRatePerSqft: 89 },
      { threshold: 1800, ratePerSqft: 120, nextRatePerSqft: 77 },
      { threshold: 2000, ratePerSqft: 116, nextRatePerSqft: 71 },
      { threshold: 2200, ratePerSqft: 112, nextRatePerSqft: 65 },
      { threshold: 2400, ratePerSqft: 108, nextRatePerSqft: 59 },
      { threshold: 2600, ratePerSqft: 104, nextRatePerSqft: 47 },
      { threshold: 2800, ratePerSqft: 100, nextRatePerSqft: 41 },
      { threshold: 3000, ratePerSqft: 96, nextRatePerSqft: 35 },
    ],
    budgetAllocation: {
      renovation: 1.0,
      refurbishment1st: 0.08,
      refurbishment2nd: 0.16,
      refurbishment3rd: 0.7,
      rebranding: 0.15,
      reinstatement: 0.12,
    },
    hasBlueSpirit: false,
    hasMaleBed: true,
    hasMealPlan: false,
    capacityRules: {
      '1201 - 1400': {
        minCR: 2, maxCR: 3,
        minTR: 5, maxTR: 10,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 2, maxMaleBed: 2,
        minTotalBeds: 7, maxTotalBeds: 12,
      },
      '1401 - 1600': {
        minCR: 2, maxCR: 3,
        minTR: 7, maxTR: 12,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 2, maxMaleBed: 3,
        minTotalBeds: 9, maxTotalBeds: 15,
      },
      '1601 - 1800': {
        minCR: 3, maxCR: 4,
        minTR: 9, maxTR: 14,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 2, maxMaleBed: 3,
        minTotalBeds: 11, maxTotalBeds: 17,
      },
      '1801 - 2000': {
        minCR: 3, maxCR: 4,
        minTR: 11, maxTR: 15,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 3, maxMaleBed: 4,
        minTotalBeds: 14, maxTotalBeds: 19,
      },
      '2001 - 2200': {
        minCR: 3, maxCR: 4,
        minTR: 13, maxTR: 17,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 3, maxMaleBed: 4,
        minTotalBeds: 16, maxTotalBeds: 21,
      },
      '2201 above': {
        minCR: 3, maxCR: 4,
        minTR: 18, maxTR: 23,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 3, maxMaleBed: 4,
        minTotalBeds: 18, maxTotalBeds: 23,
      },
    },
  },
  Dorra: {
    brand: 'Dorra',
    costTiers: [
      { threshold: 1200, ratePerSqft: 138, nextRatePerSqft: 108 },
      { threshold: 1400, ratePerSqft: 135, nextRatePerSqft: 103 },
      { threshold: 1600, ratePerSqft: 131, nextRatePerSqft: 97 },
      { threshold: 1800, ratePerSqft: 128, nextRatePerSqft: 86 },
      { threshold: 2000, ratePerSqft: 124, nextRatePerSqft: 81 },
      { threshold: 2200, ratePerSqft: 120, nextRatePerSqft: 76 },
      { threshold: 2400, ratePerSqft: 116, nextRatePerSqft: 70 },
      { threshold: 2600, ratePerSqft: 113, nextRatePerSqft: 59 },
      { threshold: 2800, ratePerSqft: 109, nextRatePerSqft: 54 },
      { threshold: 3000, ratePerSqft: 105, nextRatePerSqft: 49 },
    ],
    budgetAllocation: {
      renovation: 1.0,
      refurbishment1st: 0.05,
      refurbishment2nd: 0.08,
      refurbishment3rd: 0.7,
      rebranding: 0.15,
      reinstatement: 0.12,
    },
    hasBlueSpirit: true,
    hasMaleBed: false,
    hasMealPlan: true,
    capacityRules: {
      'Min 1400': {
        minCR: 2, maxCR: 3,
        minTR: 4, maxTR: 7,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 2, maxBlueSpirit: 4,
        minMealPlan: 1, maxMealPlan: 2,
        minTotalBeds: 6, maxTotalBeds: 11,
      },
      '1401 - 1600': {
        minCR: 2, maxCR: 4,
        minTR: 5, maxTR: 8,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 2, maxBlueSpirit: 4,
        minMealPlan: 1, maxMealPlan: 2,
        minTotalBeds: 7, maxTotalBeds: 12,
      },
      '1601 - 1800': {
        minCR: 3, maxCR: 4,
        minTR: 7, maxTR: 10,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 3, maxBlueSpirit: 5,
        minMealPlan: 1, maxMealPlan: 2,
        minTotalBeds: 10, maxTotalBeds: 15,
      },
      '1801 - 2000': {
        minCR: 3, maxCR: 4,
        minTR: 9, maxTR: 12,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 4, maxBlueSpirit: 5,
        minMealPlan: 1, maxMealPlan: 2,
        minTotalBeds: 13, maxTotalBeds: 17,
      },
      '2001 - 2200': {
        minCR: 3, maxCR: 4,
        minTR: 10, maxTR: 13,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 4, maxBlueSpirit: 5,
        minMealPlan: 2, maxMealPlan: 2,
        minTotalBeds: 14, maxTotalBeds: 18,
      },
      '2201 - 2400': {
        minCR: 3, maxCR: 4,
        minTR: 12, maxTR: 15,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 4, maxBlueSpirit: 5,
        minMealPlan: 2, maxMealPlan: 2,
        minTotalBeds: 16, maxTotalBeds: 20,
      },
      '2400 above': {
        minCR: 3, maxCR: 4,
        minTR: 14, maxTR: 17,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 4, maxBlueSpirit: 5,
        minMealPlan: 2, maxMealPlan: 2,
        minTotalBeds: 18, maxTotalBeds: 22,
      },
    },
  },
  Shakura: {
    brand: 'Shakura',
    costTiers: [
      { threshold: 1200, ratePerSqft: 131, nextRatePerSqft: 100 },
      { threshold: 1400, ratePerSqft: 128, nextRatePerSqft: 94 },
      { threshold: 1600, ratePerSqft: 123, nextRatePerSqft: 89 },
      { threshold: 1800, ratePerSqft: 120, nextRatePerSqft: 77 },
      { threshold: 2000, ratePerSqft: 116, nextRatePerSqft: 71 },
      { threshold: 2200, ratePerSqft: 112, nextRatePerSqft: 65 },
      { threshold: 2400, ratePerSqft: 108, nextRatePerSqft: 59 },
      { threshold: 2600, ratePerSqft: 104, nextRatePerSqft: 47 },
      { threshold: 2800, ratePerSqft: 100, nextRatePerSqft: 41 },
      { threshold: 3000, ratePerSqft: 96, nextRatePerSqft: 35 },
    ],
    budgetAllocation: {
      renovation: 1.0,
      refurbishment1st: 0.05,
      refurbishment2nd: 0.08,
      refurbishment3rd: 0.7,
      rebranding: 0.15,
      reinstatement: 0.12,
    },
    hasBlueSpirit: false,
    hasMaleBed: true,
    hasMealPlan: false,
    capacityRules: {
      '1201 - 1400': {
        minCR: 2, maxCR: 3,
        minTR: 5, maxTR: 10,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 2, maxMaleBed: 2,
        minTotalBeds: 7, maxTotalBeds: 12,
      },
      '1401 - 1600': {
        minCR: 2, maxCR: 3,
        minTR: 7, maxTR: 12,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 2, maxMaleBed: 3,
        minTotalBeds: 9, maxTotalBeds: 15,
      },
      '1601 - 1800': {
        minCR: 3, maxCR: 4,
        minTR: 9, maxTR: 14,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 2, maxMaleBed: 3,
        minTotalBeds: 11, maxTotalBeds: 17,
      },
      '1801 - 2000': {
        minCR: 3, maxCR: 4,
        minTR: 11, maxTR: 15,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 3, maxMaleBed: 4,
        minTotalBeds: 14, maxTotalBeds: 19,
      },
      '2001 - 2200': {
        minCR: 3, maxCR: 4,
        minTR: 13, maxTR: 17,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 3, maxMaleBed: 4,
        minTotalBeds: 16, maxTotalBeds: 21,
      },
      '2201 above': {
        minCR: 3, maxCR: 4,
        minTR: 15, maxTR: 19,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 3, maxMaleBed: 4,
        minTotalBeds: 18, maxTotalBeds: 23,
      },
    },
  },
  Jonsson: {
    brand: 'Jonsson',
    costTiers: [
      { threshold: 1200, ratePerSqft: 147, nextRatePerSqft: 114 },
      { threshold: 1400, ratePerSqft: 144, nextRatePerSqft: 108 },
      { threshold: 1600, ratePerSqft: 139, nextRatePerSqft: 102 },
      { threshold: 1800, ratePerSqft: 136, nextRatePerSqft: 90 },
      { threshold: 2000, ratePerSqft: 131, nextRatePerSqft: 84 },
      { threshold: 2200, ratePerSqft: 127, nextRatePerSqft: 78 },
      { threshold: 2400, ratePerSqft: 123, nextRatePerSqft: 72 },
      { threshold: 2600, ratePerSqft: 119, nextRatePerSqft: 60 },
      { threshold: 2800, ratePerSqft: 115, nextRatePerSqft: 54 },
      { threshold: 3000, ratePerSqft: 111, nextRatePerSqft: 48 },
    ],
    budgetAllocation: {
      renovation: 1.0,
      refurbishment1st: 0.05,
      refurbishment2nd: 0.08,
      refurbishment3rd: 0.7,
      rebranding: 0.15,
      reinstatement: 0.12,
    },
    hasBlueSpirit: false,
    hasMaleBed: false,
    hasMealPlan: false,
    capacityRules: {
      'Below 1300': {
        minCR: 2, maxCR: 3,
        minTR: 3, maxTR: 3,
        minOpenTR: 10, maxOpenTR: 12,
        minShampoo: 2, maxShampoo: 3,
        minTotalBeds: 13, maxTotalBeds: 15,
      },
      '1301 - 1500': {
        minCR: 2, maxCR: 3,
        minTR: 3, maxTR: 4,
        minOpenTR: 12, maxOpenTR: 14,
        minShampoo: 2, maxShampoo: 3,
        minTotalBeds: 15, maxTotalBeds: 18,
      },
      '1501 - 1700': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 14, maxOpenTR: 17,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 18, maxTotalBeds: 22,
      },
      '1701 - 1900': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 17, maxOpenTR: 22,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 21, maxTotalBeds: 27,
      },
      '1901 - 2100': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 19, maxOpenTR: 23,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 23, maxTotalBeds: 28,
      },
      '2101 - 2300': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 21, maxOpenTR: 24,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 25, maxTotalBeds: 29,
      },
      '2301 above': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 23, maxOpenTR: 25,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 27, maxTotalBeds: 30,
      },
    },
  },
  Victoria: {
    brand: 'Victoria',
    costTiers: [
      { threshold: 1200, ratePerSqft: 131, nextRatePerSqft: 100 },
      { threshold: 1400, ratePerSqft: 128, nextRatePerSqft: 94 },
      { threshold: 1600, ratePerSqft: 123, nextRatePerSqft: 89 },
      { threshold: 1800, ratePerSqft: 120, nextRatePerSqft: 77 },
      { threshold: 2000, ratePerSqft: 116, nextRatePerSqft: 71 },
      { threshold: 2200, ratePerSqft: 112, nextRatePerSqft: 65 },
      { threshold: 2400, ratePerSqft: 108, nextRatePerSqft: 59 },
      { threshold: 2600, ratePerSqft: 104, nextRatePerSqft: 47 },
      { threshold: 2800, ratePerSqft: 100, nextRatePerSqft: 41 },
      { threshold: 3000, ratePerSqft: 96, nextRatePerSqft: 35 },
    ],
    budgetAllocation: {
      renovation: 1.0,
      refurbishment1st: 0.05,
      refurbishment2nd: 0.08,
      refurbishment3rd: 0.7,
      rebranding: 0.15,
      reinstatement: 0.12,
    },
    hasBlueSpirit: false,
    hasMaleBed: true,
    hasMealPlan: false,
    capacityRules: {
      '1201 - 1400': {
        minCR: 2, maxCR: 3,
        minTR: 5, maxTR: 10,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 2, maxMaleBed: 2,
        minTotalBeds: 7, maxTotalBeds: 12,
      },
      '1401 - 1600': {
        minCR: 2, maxCR: 3,
        minTR: 7, maxTR: 12,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 2, maxMaleBed: 3,
        minTotalBeds: 9, maxTotalBeds: 15,
      },
      '1601 - 1800': {
        minCR: 3, maxCR: 4,
        minTR: 9, maxTR: 14,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 2, maxMaleBed: 3,
        minTotalBeds: 11, maxTotalBeds: 17,
      },
      '1801 - 2000': {
        minCR: 3, maxCR: 4,
        minTR: 11, maxTR: 15,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 3, maxMaleBed: 4,
        minTotalBeds: 14, maxTotalBeds: 19,
      },
      '2001 - 2200': {
        minCR: 3, maxCR: 4,
        minTR: 13, maxTR: 17,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 3, maxMaleBed: 4,
        minTotalBeds: 16, maxTotalBeds: 21,
      },
      '2201 above': {
        minCR: 3, maxCR: 4,
        minTR: 15, maxTR: 19,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 3, maxMaleBed: 4,
        minTotalBeds: 18, maxTotalBeds: 23,
      },
    },
  },
};

export function getBrandRules(brand: BrandKey): BrandRules {
  const rules = brandRulesMap[brand];
  if (!rules) throw new Error(`No rules defined for brand: ${brand}`);
  return rules;
}