import { BrandRules, BrandKey } from '@/types/capex';

export const brandRulesMap: Record<BrandKey, BrandRules> = {
  'Yun Nam': {
    brand: 'Yun Nam',
    baseRenovationCostPerSqft: 147,
    nextTierCostPerSqft: 114,
    tierThresholds: [1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 2800, 3000],
    budgetAllocation: {
      renovation: 1.0,
      refurbishment1st: 0.08,
      refurbishment2nd: 0.16,
      refurbishment3rd: 0.7,
      rebranding: 0.15,
      reinstatement: 0.12,
    },
    hasBlueSpirit: false,
    hasMaleBed: false,
    hasMealPlan: false,
    capacityRules: {
      'Below 1300': {
        minCR: 2, maxCR: 3,
        minTR: 3, maxTR: 3,
        minOpenTR: 10, maxOpenTR: 12,
        minShampoo: 2, maxShampoo: 3,
        minTotalBeds: 13, maxTotalBeds: 15,
      },
      '1301 - 1500': {
        minCR: 2, maxCR: 3,
        minTR: 3, maxTR: 4,
        minOpenTR: 12, maxOpenTR: 14,
        minShampoo: 2, maxShampoo: 3,
        minTotalBeds: 15, maxTotalBeds: 16,
      },
      '1501 - 1700': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 14, maxOpenTR: 17,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 18, maxTotalBeds: 22,
      },
      '1701 - 1900': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 17, maxOpenTR: 22,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 21, maxTotalBeds: 27,
      },
      '1901 - 2100': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 19, maxOpenTR: 23,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 23, maxTotalBeds: 28,
      },
      '2101 - 2300': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 21, maxOpenTR: 24,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 25, maxTotalBeds: 29,
      },
      '2301 above': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 23, maxOpenTR: 25,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 27, maxTotalBeds: 30,
      },
    },
  },
  London: {
    brand: 'London',
    baseRenovationCostPerSqft: 162,
    nextTierCostPerSqft: 127,
    tierThresholds: [1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 2800, 3000],
    budgetAllocation: {
      renovation: 1.0,
      refurbishment1st: 0.08,
      refurbishment2nd: 0.16,
      refurbishment3rd: 0.7,
      rebranding: 0.15,
      reinstatement: 0.12,
    },
    hasBlueSpirit: true,
    hasMaleBed: false,
    hasMealPlan: false,
    capacityRules: {
      'Min 1400': {
        minCR: 2, maxCR: 3,
        minTR: 4, maxTR: 6,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 2, maxBlueSpirit: 3,
        minTotalBeds: 6, maxTotalBeds: 9,
      },
      '1401 - 1600': {
        minCR: 3, maxCR: 4,
        minTR: 5, maxTR: 7,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 2, maxBlueSpirit: 3,
        minTotalBeds: 7, maxTotalBeds: 10,
      },
      '1601 - 1800': {
        minCR: 3, maxCR: 4,
        minTR: 7, maxTR: 9,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 2, maxBlueSpirit: 4,
        minTotalBeds: 9, maxTotalBeds: 13,
      },
      '1801 - 2000': {
        minCR: 3, maxCR: 4,
        minTR: 9, maxTR: 11,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 2, maxBlueSpirit: 4,
        minTotalBeds: 11, maxTotalBeds: 15,
      },
      '2001 - 2200': {
        minCR: 3, maxCR: 4,
        minTR: 10, maxTR: 12,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 2, maxBlueSpirit: 4,
        minTotalBeds: 12, maxTotalBeds: 16,
      },
      '2201 - 2400': {
        minCR: 3, maxCR: 4,
        minTR: 12, maxTR: 14,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 2, maxBlueSpirit: 4,
        minTotalBeds: 14, maxTotalBeds: 16,
      },
      '2400 above': {
        minCR: 3, maxCR: 4,
        minTR: 14, maxTR: 16,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 2, maxBlueSpirit: 4,
        minTotalBeds: 16, maxTotalBeds: 20,
      },
    },
  },
  'New York': {
    brand: 'New York',
    baseRenovationCostPerSqft: 131,
    nextTierCostPerSqft: 100,
    tierThresholds: [1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 2800, 3000],
    budgetAllocation: {
      renovation: 1.0,
      refurbishment1st: 0.08,
      refurbishment2nd: 0.16,
      refurbishment3rd: 0.7,
      rebranding: 0.15,
      reinstatement: 0.12,
    },
    hasBlueSpirit: false,
    hasMaleBed: true,
    hasMealPlan: false,
    capacityRules: {
      '1201 - 1400': {
        minCR: 2, maxCR: 3,
        minTR: 5, maxTR: 10,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 2, maxMaleBed: 2,
        minTotalBeds: 7, maxTotalBeds: 12,
      },
      '1401 - 1600': {
        minCR: 2, maxCR: 3,
        minTR: 7, maxTR: 12,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 2, maxMaleBed: 3,
        minTotalBeds: 9, maxTotalBeds: 15,
      },
      '1601 - 1800': {
        minCR: 3, maxCR: 4,
        minTR: 9, maxTR: 14,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 2, maxMaleBed: 3,
        minTotalBeds: 11, maxTotalBeds: 17,
      },
      '1801 - 2000': {
        minCR: 3, maxCR: 4,
        minTR: 11, maxTR: 15,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 3, maxMaleBed: 4,
        minTotalBeds: 14, maxTotalBeds: 19,
      },
      '2001 - 2200': {
        minCR: 3, maxCR: 4,
        minTR: 13, maxTR: 17,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 3, maxMaleBed: 4,
        minTotalBeds: 16, maxTotalBeds: 21,
      },
      '2201 above': {
        minCR: 3, maxCR: 4,
        minTR: 18, maxTR: 23,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 3, maxMaleBed: 4,
        minTotalBeds: 18, maxTotalBeds: 23,
      },
    },
  },
  Dorra: {
    brand: 'Dorra',
    baseRenovationCostPerSqft: 138,
    nextTierCostPerSqft: 108,
    tierThresholds: [1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 2800, 3000],
    budgetAllocation: {
      renovation: 1.0,
      refurbishment1st: 0.05,
      refurbishment2nd: 0.08,
      refurbishment3rd: 0.7,
      rebranding: 0.15,
      reinstatement: 0.12,
    },
    hasBlueSpirit: true,
    hasMaleBed: false,
    hasMealPlan: true,
    capacityRules: {
      'Min 1400': {
        minCR: 2, maxCR: 3,
        minTR: 4, maxTR: 7,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 2, maxBlueSpirit: 4,
        minMealPlan: 1, maxMealPlan: 2,
        minTotalBeds: 6, maxTotalBeds: 11,
      },
      '1401 - 1600': {
        minCR: 2, maxCR: 4,
        minTR: 5, maxTR: 8,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 2, maxBlueSpirit: 4,
        minMealPlan: 1, maxMealPlan: 2,
        minTotalBeds: 7, maxTotalBeds: 12,
      },
      '1601 - 1800': {
        minCR: 3, maxCR: 4,
        minTR: 7, maxTR: 10,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 3, maxBlueSpirit: 5,
        minMealPlan: 1, maxMealPlan: 2,
        minTotalBeds: 10, maxTotalBeds: 15,
      },
      '1801 - 2000': {
        minCR: 3, maxCR: 4,
        minTR: 9, maxTR: 12,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 4, maxBlueSpirit: 5,
        minMealPlan: 1, maxMealPlan: 2,
        minTotalBeds: 13, maxTotalBeds: 17,
      },
      '2001 - 2200': {
        minCR: 3, maxCR: 4,
        minTR: 10, maxTR: 13,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 4, maxBlueSpirit: 5,
        minMealPlan: 2, maxMealPlan: 2,
        minTotalBeds: 14, maxTotalBeds: 18,
      },
      '2201 - 2400': {
        minCR: 3, maxCR: 4,
        minTR: 12, maxTR: 15,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 4, maxBlueSpirit: 5,
        minMealPlan: 2, maxMealPlan: 2,
        minTotalBeds: 16, maxTotalBeds: 20,
      },
      '2400 above': {
        minCR: 3, maxCR: 4,
        minTR: 14, maxTR: 17,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minBlueSpirit: 4, maxBlueSpirit: 5,
        minMealPlan: 2, maxMealPlan: 2,
        minTotalBeds: 18, maxTotalBeds: 22,
      },
    },
  },
  Shakura: {
    brand: 'Shakura',
    baseRenovationCostPerSqft: 131,
    nextTierCostPerSqft: 100,
    tierThresholds: [1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 2800, 3000],
    budgetAllocation: {
      renovation: 1.0,
      refurbishment1st: 0.05,
      refurbishment2nd: 0.08,
      refurbishment3rd: 0.7,
      rebranding: 0.15,
      reinstatement: 0.12,
    },
    hasBlueSpirit: false,
    hasMaleBed: true,
    hasMealPlan: false,
    capacityRules: {
      '1201 - 1400': {
        minCR: 2, maxCR: 3,
        minTR: 5, maxTR: 10,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 2, maxMaleBed: 2,
        minTotalBeds: 7, maxTotalBeds: 12,
      },
      '1401 - 1600': {
        minCR: 2, maxCR: 3,
        minTR: 7, maxTR: 12,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 2, maxMaleBed: 3,
        minTotalBeds: 9, maxTotalBeds: 15,
      },
      '1601 - 1800': {
        minCR: 3, maxCR: 4,
        minTR: 9, maxTR: 14,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 2, maxMaleBed: 3,
        minTotalBeds: 11, maxTotalBeds: 17,
      },
      '1801 - 2000': {
        minCR: 3, maxCR: 4,
        minTR: 11, maxTR: 15,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 3, maxMaleBed: 4,
        minTotalBeds: 14, maxTotalBeds: 19,
      },
      '2001 - 2200': {
        minCR: 3, maxCR: 4,
        minTR: 13, maxTR: 17,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 3, maxMaleBed: 4,
        minTotalBeds: 16, maxTotalBeds: 21,
      },
      '2201 above': {
        minCR: 3, maxCR: 4,
        minTR: 15, maxTR: 19,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 3, maxMaleBed: 4,
        minTotalBeds: 18, maxTotalBeds: 23,
      },
    },
  },
  Jonsson: {
    brand: 'Jonsson',
    baseRenovationCostPerSqft: 147,
    nextTierCostPerSqft: 114,
    tierThresholds: [1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 2800, 3000],
    budgetAllocation: {
      renovation: 1.0,
      refurbishment1st: 0.05,
      refurbishment2nd: 0.08,
      refurbishment3rd: 0.7,
      rebranding: 0.15,
      reinstatement: 0.12,
    },
    hasBlueSpirit: false,
    hasMaleBed: false,
    hasMealPlan: false,
    capacityRules: {
      'Below 1300': {
        minCR: 2, maxCR: 3,
        minTR: 3, maxTR: 3,
        minOpenTR: 10, maxOpenTR: 12,
        minShampoo: 2, maxShampoo: 3,
        minTotalBeds: 13, maxTotalBeds: 15,
      },
      '1301 - 1500': {
        minCR: 2, maxCR: 3,
        minTR: 3, maxTR: 4,
        minOpenTR: 12, maxOpenTR: 14,
        minShampoo: 2, maxShampoo: 3,
        minTotalBeds: 15, maxTotalBeds: 18,
      },
      '1501 - 1700': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 14, maxOpenTR: 17,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 18, maxTotalBeds: 22,
      },
      '1701 - 1900': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 17, maxOpenTR: 22,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 21, maxTotalBeds: 27,
      },
      '1901 - 2100': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 19, maxOpenTR: 23,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 23, maxTotalBeds: 28,
      },
      '2101 - 2300': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 21, maxOpenTR: 24,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 25, maxTotalBeds: 29,
      },
      '2301 above': {
        minCR: 3, maxCR: 4,
        minTR: 4, maxTR: 5,
        minOpenTR: 23, maxOpenTR: 25,
        minShampoo: 3, maxShampoo: 4,
        minTotalBeds: 27, maxTotalBeds: 30,
      },
    },
  },
  Victoria: {
    brand: 'Victoria',
    baseRenovationCostPerSqft: 131,
    nextTierCostPerSqft: 100,
    tierThresholds: [1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 2800, 3000],
    budgetAllocation: {
      renovation: 1.0,
      refurbishment1st: 0.05,
      refurbishment2nd: 0.08,
      refurbishment3rd: 0.7,
      rebranding: 0.15,
      reinstatement: 0.12,
    },
    hasBlueSpirit: false,
    hasMaleBed: true,
    hasMealPlan: false,
    capacityRules: {
      '1201 - 1400': {
        minCR: 2, maxCR: 3,
        minTR: 5, maxTR: 10,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 2, maxMaleBed: 2,
        minTotalBeds: 7, maxTotalBeds: 12,
      },
      '1401 - 1600': {
        minCR: 2, maxCR: 3,
        minTR: 7, maxTR: 12,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 2, maxMaleBed: 3,
        minTotalBeds: 9, maxTotalBeds: 15,
      },
      '1601 - 1800': {
        minCR: 3, maxCR: 4,
        minTR: 9, maxTR: 14,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 2, maxMaleBed: 3,
        minTotalBeds: 11, maxTotalBeds: 17,
      },
      '1801 - 2000': {
        minCR: 3, maxCR: 4,
        minTR: 11, maxTR: 15,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 3, maxMaleBed: 4,
        minTotalBeds: 14, maxTotalBeds: 19,
      },
      '2001 - 2200': {
        minCR: 3, maxCR: 4,
        minTR: 13, maxTR: 17,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 3, maxMaleBed: 4,
        minTotalBeds: 16, maxTotalBeds: 21,
      },
      '2201 above': {
        minCR: 3, maxCR: 4,
        minTR: 15, maxTR: 19,
        minOpenTR: 0, maxOpenTR: 0,
        minShampoo: 0, maxShampoo: 0,
        minMaleBed: 3, maxMaleBed: 4,
        minTotalBeds: 18, maxTotalBeds: 23,
      },
    },
  },
};

export function getBrandRules(brand: BrandKey): BrandRules {
  const rules = brandRulesMap[brand];
  if (!rules) throw new Error(`No rules defined for brand: ${brand}`);
  return rules;
}