// app/privacy/page.tsx
"use client";

import {
  DocumentHeader,
  TableOfContents,
  SectionHeader,
  LegalList,
  CalloutBox,
} from '@/components/privacy';

export default function PrivacyPage() {
  const tocItems = [
    { id: 'section1', label: '1. Categories of Collected Information' },
    { id: 'section2', label: '2. Purpose and Lawful Basis' },
    { id: 'section3', label: '3. Data Sharing, Retention & Access' },
    { id: 'section4', label: '4. Data Security & Safeguards' },
    { id: 'section5', label: '5. Your Privacy Rights' },
    { id: 'section6', label: '6. DPO & Contact' },
    { id: 'section7', label: '7. Cookies & Tracking' },
    { id: 'section8', label: '8. International Data Transfers' },
    { id: 'section9', label: '9. Children\'s Privacy' },
    { id: 'section10', label: '10. Policy Updates' },
    { id: 'section11', label: '11. Compliance & Accountability' },
    { id: 'appendix', label: 'Appendix A: Definitions' },
  ];

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 py-12 px-4 sm:px-6 lg:px-8 print:py-6 print:px-4 print:bg-white print:text-black">
      <div className="max-w-5xl mx-auto relative">
        {/* Print Button */}
        <div className="absolute top-0 right-0 z-10 print:hidden">
          <button
            onClick={handlePrint}
            className="inline-flex items-center gap-2 px-4 py-2 bg-cyan-700 hover:bg-cyan-800 text-white text-sm font-medium rounded-lg transition shadow-sm"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
            </svg>
            Print
          </button>
        </div>

        <DocumentHeader
          title="Privacy Policy & Data Practices"
          effectiveDate="19 June 2026"
          version="1.0"
          lastUpdated="19 June 2026"
        />

        <TableOfContents items={tocItems} />

        <div className="prose prose-slate dark:prose-invert max-w-none prose-headings:font-semibold prose-headings:tracking-tight prose-p:text-slate-700 dark:prose-p:text-slate-300 prose-p:leading-relaxed prose-p:text-base md:prose-p:text-lg prose-a:text-cyan-600 dark:prose-a:text-cyan-400 prose-ul:space-y-2 prose-li:marker:text-slate-500 print:prose-p:text-black print:prose-headings:text-black print:prose-a:text-black print:prose-strong:text-black">

          <p className="lead text-slate-600 dark:text-slate-300 text-lg">
            This Privacy Policy and Data Practices Document (the <strong>"Policy"</strong>) governs the collection, processing, storage, and protection of personal and corporate data submitted to or generated by the TMS Project &amp; Cost Management System (the <strong>"Platform"</strong> or <strong>"System"</strong>), operated by Beauty One International Pte Ltd. (<strong>"Company,"</strong> <strong>"we,"</strong> <strong>"our,"</strong> or <strong>"us"</strong>).
          </p>

          <p>This Policy applies to all users of the Platform, including:</p>
          <LegalList
            items={[
              <span key="1">
                <strong>Internal Team Members:</strong> Employees, contractors, and authorised personnel who access the Platform for project governance, tender management, and operational oversight.
              </span>,
              <span key="2">
                <strong>External Contractors:</strong> Third‑party contracting firms, vendors, and personnel who submit tender bids, commercial proposals, and compliance documentation through the Platform.
              </span>,
            ]}
          />

          <CalloutBox type="info">
            <strong>Our Commitment:</strong> We are committed to protecting the privacy and security of all data processed through the Platform. This Policy complies with the Singapore Personal Data Protection Act (<strong>PDPA</strong>), and adheres to best practices recommended by the Consumers Association of Singapore (<strong>CASE</strong>) and the Infocomm Media Development Authority (<strong>IMDA</strong>).
          </CalloutBox>

          <hr className="my-12 border-slate-200 dark:border-slate-800" />

          <SectionHeader id="section1" level={2} summary="We collect only the data necessary for procurement, project governance, and compliance – across four distinct categories.">
            SECTION 1: CATEGORIES OF COLLECTED INFORMATION
          </SectionHeader>
          <p>The Platform collects and processes information across four principal categories, with strict data segmentation to preserve commercial confidentiality.</p>

          <SectionHeader level={3}>1.1 Corporate &amp; Compliance Data</SectionHeader>
          <LegalList
            items={[
              <span key="1-1"><strong>Company Registration:</strong> Business registration numbers, certificates of incorporation, UEN/tax identification numbers</span>,
              <span key="1-2"><strong>Financial Standing:</strong> Audited financial statements, bank confirmation letters, credit references, proof of insurance coverage</span>,
              <span key="1-3"><strong>Compliance Credentials:</strong> Industry accreditations, safety compliance documentation, professional licenses</span>,
              <span key="1-4"><strong>Performance Metrics:</strong> Historical project completion records, quality assessment scores, on‑time delivery tracking</span>,
              <span key="1-5"><strong>Audit Records:</strong> Financial transactions, approval workflows, and compliance verification events</span>,
            ]}
          />

          <SectionHeader level={3}>1.2 Personnel &amp; Contact Data</SectionHeader>
          <LegalList
            items={[
              <span key="2-1"><strong>Direct Identifiers:</strong> Full name, official job title, corporate email address, direct telephone numbers</span>,
              <span key="2-2"><strong>Role‑Based Attributes:</strong> Employment status, departmental assignment, authority/approval rights within the Platform</span>,
              <span key="2-3"><strong>Professional History:</strong> Curriculum vitae summaries, professional certifications, skills profiles (where submitted voluntarily)</span>,
              <span key="2-4"><strong>User Credentials:</strong> System login credentials, multi‑factor authentication tokens, access role assignments</span>,
            ]}
          />

          <SectionHeader level={3}>1.3 Commercial &amp; Pricing Data</SectionHeader>
          <LegalList
            items={[
              <span key="3-1"><strong>Bill of Quantities (BQ):</strong> Detailed itemised breakdowns of materials, labour, equipment, and cost components</span>,
              <span key="3-2"><strong>Line‑Item Pricing:</strong> Unit rates, extended totals, discount structures applied to bid proposals</span>,
              <span key="3-3"><strong>Bidding Histories:</strong> Historical records of tender submissions, outcomes (awarded, declined, withdrawn), contract values</span>,
              <span key="3-4"><strong>Contractual Documentation:</strong> Signed contracts, variation orders, amendment records, scope‑of‑work deliverables</span>,
              <span key="3-5"><strong>Estimated Budget Data:</strong> Internal cost projections, budget ceilings, financial benchmarking data for evaluation</span>,
            ]}
          />

          <SectionHeader level={3}>1.4 Technical Logs &amp; System Telemetry</SectionHeader>
          <LegalList
            items={[
              <span key="4-1"><strong>Access Logs:</strong> Records of authentication attempts, session duration, logout times</span>,
              <span key="4-2"><strong>Interaction Logs:</strong> Feature usage, document uploads/edits, navigation patterns</span>,
              <span key="4-3"><strong>Device Identifiers:</strong> IP addresses, browser type and version, operating system details, device fingerprints</span>,
              <span key="4-4"><strong>Audit Trails:</strong> Immutable records of all data changes—who accessed, modified, or approved data elements</span>,
              <span key="4-5"><strong>System Performance:</strong> API call logs, error logs, system response metrics</span>,
            ]}
          />

          <CalloutBox type="highlight">
            <strong>Data Minimisation:</strong> The Platform collects only data strictly necessary for the purposes described in Section 2, in accordance with data minimisation principles under the PDPA.
          </CalloutBox>

          <hr className="my-12 border-slate-200 dark:border-slate-800" />

          <SectionHeader id="section2" level={2} summary="Processing is grounded in legitimate purposes – contract performance, security, and legal compliance.">
            SECTION 2: PURPOSE AND LAWFUL BASIS OF PROCESSING
          </SectionHeader>
          <p>All processing activities are conducted for legitimate purposes and in accordance with the PDPA.</p>

          <SectionHeader level={3}>2.1 Purposes of Processing</SectionHeader>
          <LegalList
            variant="decimal"
            items={[
              <span key="p1">
                <strong>Contractual &amp; Pre‑Contractual Obligations</strong>
                <LegalList
                  items={[
                    <span key="p1-1">Facilitate contractor registration and tender submission</span>,
                    <span key="p1-2">Evaluate tenders against pre‑defined criteria (cost, capability, compliance)</span>,
                    <span key="p1-3">Communicate tender outcomes to participating parties</span>,
                    <span key="p1-4">Administer awarded contracts, including project governance and milestone tracking</span>,
                  ]}
                />
              </span>,
              <span key="p2">
                <strong>Project Governance &amp; Cost Optimisation</strong>
                <LegalList
                  items={[
                    <span key="p2-1">Cost variance analysis and budget tracking</span>,
                    <span key="p2-2">Risk identification and mitigation</span>,
                    <span key="p2-3">Performance benchmarking and continuous improvement</span>,
                    <span key="p2-4">Audit‑ready financial reporting</span>,
                  ]}
                />
              </span>,
              <span key="p3">
                <strong>Platform Security &amp; Fraud Prevention</strong>
                <LegalList
                  items={[
                    <span key="p3-1">Corporate verification and identity authentication</span>,
                    <span key="p3-2">Anomaly detection and suspicious activity monitoring</span>,
                    <span key="p3-3">Access control enforcement</span>,
                    <span key="p3-4">Security incident investigation and response</span>,
                  ]}
                />
              </span>,
              <span key="p4">
                <strong>Legal &amp; Regulatory Compliance</strong>
                <LegalList
                  items={[
                    <span key="p4-1">Retention of financial records for tax and statutory audit requirements</span>,
                    <span key="p4-2">Compliance with requests from regulatory authorities or law enforcement</span>,
                    <span key="p4-3">Adherence to industry‑specific reporting obligations</span>,
                  ]}
                />
              </span>,
            ]}
          />

          <SectionHeader level={3}>2.2 Lawful Bases under PDPA</SectionHeader>
          <p>Under the PDPA, our processing is based on the following lawful grounds:</p>
          <LegalList
            items={[
              <span key="lb1"><strong>Consent:</strong> Where you have provided clear consent for specific processing activities.</span>,
              <span key="lb2"><strong>Contractual Necessity:</strong> Processing necessary to perform a contract with you or to take pre‑contractual steps at your request.</span>,
              <span key="lb3"><strong>Legal Obligation:</strong> Processing required to comply with a legal obligation (e.g., tax, audit, regulatory reporting).</span>,
              <span key="lb4"><strong>Legitimate Interests:</strong> Processing necessary for our legitimate business interests (platform security, fraud prevention, service improvement) that do not override your rights and freedoms.</span>,
            ]}
          />

          <CalloutBox type="warning">
            <strong>Legitimate Interests Assessment:</strong> We have conducted a Legitimate Interests Assessment (LIA) confirming that processing for platform security, fraud prevention, and service optimisation is necessary, proportionate, and does not prejudice your rights.
          </CalloutBox>

          <hr className="my-12 border-slate-200 dark:border-slate-800" />

          <SectionHeader id="section3" level={2} summary="Data is never sold. Commercial pricing is strictly siloed – competitors never see each other's bids.">
            SECTION 3: STRICT DATA SHARING, RETENTION, AND ACCESS GOVERNANCE
          </SectionHeader>

          <SectionHeader level={3}>3.1 Data Sharing — Confidentiality &amp; Siloing</SectionHeader>
          <p>We maintain strict data siloing and confidentiality protocols:</p>
          <LegalList
            items={[
              <span key="3-1-1"><strong>No Sale of Data:</strong> We do not sell, rent, or trade personal data to third parties for marketing or commercial purposes.</span>,
              <span key="3-1-2"><strong>Commercial Bid Confidentiality:</strong> Bid pricing, commercial proposals, and BQ data are strictly segregated and never shared with competing contractors.</span>,
              <span key="3-1-3"><strong>Internal Evaluation Data:</strong> Evaluation scores, assessment notes, and award recommendations are accessible only to authorised internal evaluators.</span>,
              <span key="3-1-4"><strong>Need‑to‑Know Access:</strong> Access to any data category is granted strictly on a need‑to‑know basis, with role‑based permissions enforcing least‑privilege access.</span>,
            ]}
          />
          <p><strong>Permitted Disclosures</strong></p>
          <LegalList
            items={[
              <span key="3-1-5"><strong>Internal Access:</strong> Authorised personnel granted access strictly on a need‑to‑know basis.</span>,
              <span key="3-1-6"><strong>Service Providers:</strong> Third‑party providers (cloud hosting, security monitoring) bound by strict data processing agreements (DPAs).</span>,
              <span key="3-1-7"><strong>Regulatory Authorities:</strong> Where required by applicable law or valid legal request.</span>,
              <span key="3-1-8"><strong>Successor Entities:</strong> In the event of merger, acquisition, or corporate restructuring, subject to continued compliance with this Policy.</span>,
            ]}
          />

          <SectionHeader level={3}>3.2 Data Retention Parameters</SectionHeader>
          <div className="overflow-x-auto my-6">
            <table className="min-w-full text-sm border border-slate-200 dark:border-slate-700">
              <thead className="bg-slate-50 dark:bg-slate-800/50">
                <tr>
                  <th className="px-5 py-3 text-left font-semibold">Data Category</th>
                  <th className="px-5 py-3 text-left font-semibold">Retention Period</th>
                  <th className="px-5 py-3 text-left font-semibold">Rationale</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-t border-slate-200 dark:border-slate-700"><td className="px-5 py-3">Financial Audit Records</td><td className="px-5 py-3">7 years from end of financial year</td><td className="px-5 py-3">Statutory audit and regulatory compliance</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/30"><td className="px-5 py-3">Commercial &amp; Pricing Data</td><td className="px-5 py-3">7 years</td><td className="px-5 py-3">Tax and financial audit compliance</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700"><td className="px-5 py-3">Contractual Documents</td><td className="px-5 py-3">7 years from contract expiry/termination</td><td className="px-5 py-3">Legal claims limitation periods</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/30"><td className="px-5 py-3">Bidder Portfolios</td><td className="px-5 py-3">5 years</td><td className="px-5 py-3">Maintain historical contractor profiles for future procurement cycles</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700"><td className="px-5 py-3">Active Tender Records</td><td className="px-5 py-3">Duration of tender process + 3 years</td><td className="px-5 py-3">Facilitate post‑tender queries, audits, historical reference</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/30"><td className="px-5 py-3">Access &amp; Technical Logs</td><td className="px-5 py-3">2 years</td><td className="px-5 py-3">Security monitoring, incident investigation, forensic analysis</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700"><td className="px-5 py-3">Declined Tender Data</td><td className="px-5 py-3">2 years (post‑closing)</td><td className="px-5 py-3">Permit fair challenge processes and historical analysis</td></tr>
              </tbody>
            </table>
          </div>
          <p>Data may be retained longer if required to establish, exercise, or defend a legal claim, or where mandated by applicable law. Data retained beyond the initial retention period is anonymised where operationally feasible.</p>
          <p><strong>Data Deletion &amp; Anonymisation</strong></p>
          <LegalList
            items={[
              <span key="del-1">Securely deleted from production systems</span>,
              <span key="del-2">Anonymised for analytical and statistical purposes where beneficial</span>,
              <span key="del-3">Archived in encrypted, access‑controlled storage for legal hold purposes</span>,
            ]}
          />

          <SectionHeader level={3}>3.3 Access Governance</SectionHeader>
          <LegalList
            items={[
              <span key="3-3-1"><strong>Role‑Based Access Control (RBAC):</strong> Access rights granted based on job function and data classification.</span>,
              <span key="3-3-2"><strong>Principle of Least Privilege:</strong> Users granted minimum access necessary to perform duties.</span>,
              <span key="3-3-3"><strong>Segregation of Duties:</strong> Conflicting roles (e.g., bid evaluation and contract award) assigned to different individuals.</span>,
              <span key="3-3-4"><strong>Access Review:</strong> Quarterly reviews ensure continued appropriateness of permissions.</span>,
              <span key="3-3-5"><strong>Access Logging:</strong> All data access events logged and retained for audit purposes.</span>,
              <span key="3-3-6"><strong>Sensitive Financial Blocks:</strong> Commercial pricing stored in isolated logical partitions with restricted access.</span>,
            ]}
          />

          <hr className="my-12 border-slate-200 dark:border-slate-800" />

          <SectionHeader id="section4" level={2} summary="We use industry‑standard encryption (TLS/AES‑256), MFA, and strict role‑based isolation to protect your data.">
            SECTION 4: DATA SECURITY AND ENTERPRISE SAFEGUARDS
          </SectionHeader>
          <p>We implement industry‑standard technical and organisational measures to protect data against unauthorised access, loss, destruction, or alteration.</p>

          <SectionHeader level={3}>4.1 Encryption Standards</SectionHeader>
          <LegalList
            items={[
              <span key="4-1-1"><strong>Data in Transit:</strong> TLS 1.2 or higher – All data transmitted between client devices and servers encrypted.</span>,
              <span key="4-1-2"><strong>Data at Rest:</strong> AES‑256 – All stored data, databases, file storage, and backups encrypted.</span>,
              <span key="4-1-3"><strong>Backup Media:</strong> AES‑256 – All backup media and portable storage devices encrypted.</span>,
            ]}
          />

          <SectionHeader level={3}>4.2 Access Controls</SectionHeader>
          <LegalList
            items={[
              <span key="4-2-1"><strong>Multi‑Factor Authentication (MFA):</strong> Mandatory for all users accessing the Platform.</span>,
              <span key="4-2-2"><strong>Single Sign‑On (SSO):</strong> Enterprise‑grade SSO for centralised identity management.</span>,
              <span key="4-2-3"><strong>Session Management:</strong> Automatic session timeouts and concurrent session controls.</span>,
              <span key="4-2-4"><strong>Password Policy:</strong> Enforced password complexity, rotation, and history requirements.</span>,
            ]}
          />

          <SectionHeader level={3}>4.3 Data Segregation &amp; Isolation</SectionHeader>
          <LegalList
            items={[
              <span key="4-3-1"><strong>Tenant Isolation:</strong> Logical separation of data belonging to different clients and contractors.</span>,
              <span key="4-3-2"><strong>Sensitive Data Redaction:</strong> Automatic redaction of sensitive financial data in non‑production environments.</span>,
              <span key="4-3-3"><strong>Staging Controls:</strong> Production data never used in development/testing without appropriate anonymisation.</span>,
            ]}
          />

          <SectionHeader level={3}>4.4 Monitoring &amp; Incident Response</SectionHeader>
          <LegalList
            items={[
              <span key="4-4-1"><strong>Continuous Monitoring:</strong> 24/7 system monitoring for security events and anomalies.</span>,
              <span key="4-4-2"><strong>Audit Logging:</strong> Comprehensive audit trails of all data access, modification, and deletion events.</span>,
              <span key="4-4-3"><strong>Incident Response Plan:</strong> Documented and tested procedures for data breach scenarios.</span>,
              <span key="4-4-4"><strong>Breach Notification:</strong> Affected data subjects and the Personal Data Protection Commission (PDPC) notified promptly in the event of a notifiable breach.</span>,
            ]}
          />

          <SectionHeader level={3}>4.5 Organisational Measures</SectionHeader>
          <LegalList
            items={[
              <span key="4-5-1"><strong>Data Protection Officer (DPO):</strong> Appointed to ensure compliance with the PDPA.</span>,
              <span key="4-5-2"><strong>Staff Training:</strong> Mandatory data privacy and security training on induction and annually.</span>,
              <span key="4-5-3"><strong>Vendor Due Diligence:</strong> All third‑party providers subject to security and privacy assessments.</span>,
              <span key="4-5-4"><strong>Data Protection by Design:</strong> Privacy and security integrated into all system development processes.</span>,
              <span key="4-5-5"><strong>Business Continuity:</strong> Redundant infrastructure, regular backups, tested disaster recovery plans.</span>,
            ]}
          />

          <hr className="my-12 border-slate-200 dark:border-slate-800" />

          <SectionHeader id="section5" level={2} summary="You have the right to access, correct, delete, and port your data. We respond within 30 days.">
            SECTION 5: YOUR PRIVACY RIGHTS
          </SectionHeader>

          <SectionHeader level={3}>5.1 Your Rights under PDPA</SectionHeader>
          <p>Under the Personal Data Protection Act (PDPA) of Singapore, you have the following rights:</p>
          <LegalList
            items={[
              <span key="5-1-1"><strong>Right of Access:</strong> Request a copy of the personal data we hold about you.</span>,
              <span key="5-1-2"><strong>Right to Correction:</strong> Request correction of inaccurate or incomplete data.</span>,
              <span key="5-1-3"><strong>Right to Withdraw Consent:</strong> Withdraw consent for processing at any time (subject to legal/contractual restrictions).</span>,
              <span key="5-1-4"><strong>Right to Data Portability:</strong> Request transfer of your data in a machine‑readable format (where applicable).</span>,
              <span key="5-1-5"><strong>Right to Lodge a Complaint:</strong> Lodge a complaint with the Personal Data Protection Commission (PDPC).</span>,
            ]}
          />

          <SectionHeader level={3}>5.2 How to Exercise Your Rights</SectionHeader>
          <p>To exercise any data subject right, please contact our Data Protection Officer using the details in Section 6. All requests will be:</p>
          <LegalList
            items={[
              <span key="5-2-1">Acknowledged within seven (7) business days of receipt.</span>,
              <span key="5-2-2">Substantively responded to within thirty (30) days (or shorter if required by law).</span>,
              <span key="5-2-3">Provided free of charge, unless manifestly unfounded or excessive.</span>,
            ]}
          />

          <hr className="my-12 border-slate-200 dark:border-slate-800" />

          <SectionHeader id="section6" level={2} summary="Our Data Protection Officer is your primary contact for any privacy concerns or requests.">
            SECTION 6: DATA PROTECTION OFFICER &amp; CONTACT INFORMATION
          </SectionHeader>
          <div className="bg-white dark:bg-slate-900/60 p-6 rounded-lg border border-slate-200 dark:border-slate-700 my-6">
            <p><strong>Data Protection Officer</strong><br />
            [Full Name, Title]<br />
            Beauty One International Pte Ltd.<br />
            2 Venture Drive, #21‑01,<br />
            VISION EXCHANGE,<br />
            Singapore 608526</p>
            <p><strong>Email:</strong> dpo@beautyone.com.sg<br />
            <strong>For data subject requests:</strong> privacy@beautyone.com.sg</p>
          </div>
          <p>All inquiries will be acknowledged within seven (7) business days and responded to in full within thirty (30) days (or as required by the PDPA).</p>

          <hr className="my-12 border-slate-200 dark:border-slate-800" />

          <SectionHeader id="section7" level={2} summary="We use essential, functional, analytical, and security cookies – you can manage preferences.">
            SECTION 7: COOKIES &amp; TRACKING TECHNOLOGIES
          </SectionHeader>
          <p>The Platform uses cookies and similar tracking technologies to enhance user experience, analyse usage, and maintain security.</p>
          <LegalList
            items={[
              <span key="7-1"><strong>Essential/Strictly Necessary:</strong> Required for Platform to function (session cookies, authentication).</span>,
              <span key="7-2"><strong>Functional:</strong> Remember preferences (language, regional settings).</span>,
              <span key="7-3"><strong>Analytical/Performance:</strong> Analyse user behaviour to improve Platform performance.</span>,
              <span key="7-4"><strong>Security:</strong> Detect and prevent security incidents.</span>,
            ]}
          />
          <p><strong>Managing Preferences:</strong> You can manage cookie preferences through browser settings. Disabling essential cookies may impact functionality. Non‑essential cookies can be opted out via the Platform&#x27;s cookie preference centre.</p>

          <hr className="my-12 border-slate-200 dark:border-slate-800" />

          <SectionHeader id="section8" level={2} summary="Your data is stored in Singapore and may be transferred to Malaysia for regional operations, with appropriate safeguards.">
            SECTION 8: INTERNATIONAL DATA TRANSFERS
          </SectionHeader>
          <p><strong>Data Storage Locations:</strong> Our primary data centre is located in Singapore. We may transfer your data to our regional counterpart in Malaysia for the purpose of operational support and business continuity.</p>
          <p><strong>Transfer Mechanisms:</strong> Where we transfer personal data outside Singapore, we will ensure that the transfer complies with the PDPA by using appropriate safeguards, such as:</p>
          <LegalList
            items={[
              <span key="8-1">Binding Corporate Rules (BCRs) or equivalent internal policies.</span>,
              <span key="8-2">Standard contractual clauses approved by the PDPC.</span>,
              <span key="8-3">Other legally recognised transfer mechanisms.</span>,
            ]}
          />
          <p><strong>Recipient Countries:</strong> Data may be transferred to Malaysia (our regional counterpart) and, where necessary, to service providers located in other jurisdictions that provide an adequate level of protection.</p>

          <hr className="my-12 border-slate-200 dark:border-slate-800" />

          <SectionHeader id="section9" level={2} summary="The Platform is not for children under 16. We do not knowingly collect their data.">
            SECTION 9: CHILDREN&#x27;S PRIVACY
          </SectionHeader>
          <p>The Platform is not intended for children under the age of 16. We do not knowingly collect personal information from children. If we become aware of such collection without verifiable parental consent, we will delete that data.</p>

          <hr className="my-12 border-slate-200 dark:border-slate-800" />

          <SectionHeader id="section10" level={2} summary="We review this Policy annually and notify you of any material changes.">
            SECTION 10: POLICY UPDATES &amp; NOTIFICATION
          </SectionHeader>
          <p><strong>Review Cycle:</strong> This Policy is reviewed annually (or as required by changes in law or operational practice).</p>
          <p><strong>Notification of Changes:</strong> Material changes will be communicated via:</p>
          <LegalList
            items={[
              <span key="10-1">Email notification to registered users.</span>,
              <span key="10-2">Platform notification (dashboard notice, login banner).</span>,
              <span key="10-3">Publication of the updated Policy with revision date clearly indicated.</span>,
            ]}
          />
          <p><strong>Effective Date:</strong> The effective date is indicated at the top. Continued use of the Platform following the effective date constitutes acceptance of the updated Policy.</p>

          <hr className="my-12 border-slate-200 dark:border-slate-800" />

          <SectionHeader id="section11" level={2} summary="We maintain detailed compliance records and conduct regular assessments to ensure accountability.">
            SECTION 11: COMPLIANCE &amp; ACCOUNTABILITY
          </SectionHeader>
          <LegalList
            items={[
              <span key="11-1"><strong>Data Protection Impact Assessments (DPIAs):</strong> Conducted for new processing activities that present a high risk to rights and freedoms of data subjects.</span>,
              <span key="11-2"><strong>Record of Processing Activities (ROPA):</strong> We maintain a detailed ROPA as required by the PDPA.</span>,
              <span key="11-3"><strong>Employee Training:</strong> All personnel with Platform access receive mandatory data privacy and security training on induction and annually thereafter.</span>,
              <span key="11-4"><strong>Regulatory Cooperation:</strong> We cooperate fully with the Personal Data Protection Commission (PDPC) in the exercise of its regulatory powers.</span>,
            ]}
          />

          <hr className="my-12 border-slate-200 dark:border-slate-800" />

          <SectionHeader id="appendix" level={2} summary="Key terms used throughout this Policy are defined here for clarity.">
            APPENDIX A: DEFINITIONS
          </SectionHeader>
          <div className="overflow-x-auto my-6">
            <table className="min-w-full text-sm border border-slate-200 dark:border-slate-700">
              <thead className="bg-slate-50 dark:bg-slate-800/50">
                <tr><th className="px-5 py-3 text-left font-semibold">Term</th><th className="px-5 py-3 text-left font-semibold">Definition</th></tr>
              </thead>
              <tbody>
                <tr className="border-t border-slate-200 dark:border-slate-700"><td className="px-5 py-3">Agent</td><td className="px-5 py-3">A third‑party contractor or firm that submits tender proposals through the Platform.</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/30"><td className="px-5 py-3">BQ</td><td className="px-5 py-3">Bill of Quantities — detailed itemised breakdown of costs submitted as part of a tender proposal.</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700"><td className="px-5 py-3">Data Controller</td><td className="px-5 py-3">The entity that determines purposes and means of processing personal data (Beauty One International Pte Ltd.).</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/30"><td className="px-5 py-3">Data Processor</td><td className="px-5 py-3">The entity that processes personal data on behalf of the Data Controller (service providers).</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700"><td className="px-5 py-3">Data Subject</td><td className="px-5 py-3">An identified or identifiable natural person whose personal data is processed.</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/30"><td className="px-5 py-3">DPA</td><td className="px-5 py-3">Data Processing Agreement — binding contract between Controller and Processor.</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700"><td className="px-5 py-3">DPO</td><td className="px-5 py-3">Data Protection Officer — individual designated to oversee data protection compliance.</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/30"><td className="px-5 py-3">PDPA</td><td className="px-5 py-3">Personal Data Protection Act (Singapore).</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700"><td className="px-5 py-3">Platform</td><td className="px-5 py-3">The TMS Project &amp; Cost Management System, including all associated software and services.</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/30"><td className="px-5 py-3">RBAC</td><td className="px-5 py-3">Role‑Based Access Control — system that restricts access based on user&#x27;s role.</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700"><td className="px-5 py-3">ROPA</td><td className="px-5 py-3">Record of Processing Activities — register of all processing activities.</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/30"><td className="px-5 py-3">Sensitive Data</td><td className="px-5 py-3">Data requiring higher protection: financial records, commercial pricing, compliance documentation.</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700"><td className="px-5 py-3">Supervisory Authority</td><td className="px-5 py-3">The Personal Data Protection Commission (PDPC) of Singapore.</td></tr>
              </tbody>
            </table>
          </div>

          <hr className="my-12 border-slate-200 dark:border-slate-800" />

          <SectionHeader level={2} summary="A quick reference for the most important points in this Policy.">
            SUMMARY OF KEY POINTS
          </SectionHeader>
          <div className="overflow-x-auto my-6">
            <table className="min-w-full text-sm border border-slate-200 dark:border-slate-700">
              <thead className="bg-slate-50 dark:bg-slate-800/50">
                <tr><th className="px-5 py-3 text-left font-semibold">Aspect</th><th className="px-5 py-3 text-left font-semibold">Summary</th></tr>
              </thead>
              <tbody>
                <tr className="border-t border-slate-200 dark:border-slate-700"><td className="px-5 py-3">Data Categories</td><td className="px-5 py-3">Corporate &amp; Compliance, Personnel &amp; Contact, Commercial &amp; Pricing, Technical Logs</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/30"><td className="px-5 py-3">Lawful Bases</td><td className="px-5 py-3">Consent, Contractual Necessity, Legal Obligation, Legitimate Interests</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700"><td className="px-5 py-3">Data Sharing</td><td className="px-5 py-3">Never sold; shared only with authorised personnel, service providers under DPAs, and for legal compliance</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/30"><td className="px-5 py-3">Data Retention</td><td className="px-5 py-3">2 to 7 years depending on category; longer for legal claims or regulatory compliance</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700"><td className="px-5 py-3">Access Controls</td><td className="px-5 py-3">RBAC, least privilege, segregation of duties, isolation of sensitive financial data, MFA</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/30"><td className="px-5 py-3">Security Measures</td><td className="px-5 py-3">AES‑256 encryption at rest, TLS 1.2+ in transit, incident response plan, business continuity</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700"><td className="px-5 py-3">Data Subject Rights</td><td className="px-5 py-3">Access, Correction, Withdraw Consent, Portability, Lodge Complaint</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/30"><td className="px-5 py-3">DPO Contact</td><td className="px-5 py-3">dpo@beautyone.com.sg — [+XX XXXX XXXX]</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700"><td className="px-5 py-3">International Transfers</td><td className="px-5 py-3">Primarily Singapore; may transfer to Malaysia under appropriate safeguards</td></tr>
                <tr className="border-t border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/30"><td className="px-5 py-3">Review Cycle</td><td className="px-5 py-3">Annual or as required by law or operational changes</td></tr>
              </tbody>
            </table>
          </div>

          <div className="mt-14 p-6 bg-slate-100 dark:bg-slate-800/50 rounded-lg border border-slate-200 dark:border-slate-700">
            <p className="text-xs text-slate-600 dark:text-slate-300">
              <strong>LEGAL DISCLAIMER</strong><br />
              This Privacy Policy is the proprietary property of Beauty One International Pte Ltd. and is provided for informational purposes only. It does not constitute legal advice. Please consult your own legal counsel to ensure compliance with all applicable laws. Beauty One International Pte Ltd. accepts no liability for reliance on this document without obtaining individual legal advice. We reserve all rights to modify, adapt, or update this document at any time without notice.
            </p>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-3">
              Copyright © 2026 Beauty One International Pte Ltd. All rights reserved. Unauthorised reproduction or distribution, in whole or in part, is strictly prohibited.
            </p>
          </div>

          <div className="mt-10 text-sm text-slate-500 dark:text-slate-400 border-t border-slate-200 dark:border-slate-700 pt-6">
            <p><strong>Document Control:</strong></p>
            <ul className="list-none pl-0 space-y-0.5">
              <li>Maintained by: Legal &amp; Compliance Function</li>
              <li>Approved by: [Name/Title]</li>
              <li>Date of Approval: [Date]</li>
              <li>Next Review Date: [Date]</li>
            </ul>
            <p className="mt-4">
              <strong>Implementation Note:</strong> For questions regarding this Privacy Policy, data protection matters, or to exercise your privacy rights, please contact our Data Protection Officer:
            </p>
            <ul className="list-none pl-0 space-y-0.5">
              <li><strong>Email:</strong> dpo@beautyone.com.sg</li>
              <li><strong>Phone:</strong> [+XX XXXX XXXX]</li>
              <li><strong>Address:</strong> 2 Venture Drive, #21-01, VISION EXCHANGE, Singapore 608526</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}