// app/privacy/page.tsx
"use client";

import Link from 'next/link';
import {
  DocumentHeader,
  TableOfContents,
  SectionHeader,
  LegalList,
} from '@/components/privacy';

export default function PrivacyPage() {
  const tocItems = [
    { id: 'section1', label: '1. Categories of Collected Information' },
    { id: 'section2', label: '2. Purpose and Lawful Basis' },
    { id: 'section3', label: '3. Data Sharing, Retention & Access' },
    { id: 'section4', label: '4. Data Security & Safeguards' },
    { id: 'section5', label: '5. Your Privacy Rights' },
    { id: 'section6', label: '6. DPO & Contact' },
    { id: 'section7', label: '7. Cookies & Tracking' },
    { id: 'section8', label: '8. Data Storage Location' },
    { id: 'section9', label: "9. Children's Privacy" },
    { id: 'section10', label: '10. Policy Updates' },
    { id: 'section11', label: '11. Compliance & Accountability' },
    { id: 'appendix', label: 'Appendix A: Definitions' },
  ];

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="min-h-screen bg-[#f7f4ee] font-sans text-slate-900 py-12 px-4 sm:px-6 lg:px-8 print:py-6 print:px-4 print:bg-white print:text-black">
      <div className="max-w-6xl mx-auto relative">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-sm text-slate-500 transition hover:text-[#15406a] print:hidden"
        >
          <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={1.75}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          Back to Home
        </Link>

        {/* Print Button */}
        <div className="absolute top-0 right-0 z-10 print:hidden">
          <button
            onClick={handlePrint}
            className="inline-flex items-center gap-2 rounded-md bg-[#15406a] px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-[#0d2d4a]"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
            </svg>
            Print
          </button>
        </div>

        <div className="mt-10 max-w-3xl">
          <DocumentHeader
            title="Privacy Policy & Data Practices"
            effectiveDate="19 June 2026"
            version="1.0"
            lastUpdated="19 June 2026"
          />
        </div>

        <div className="flex flex-col gap-8 md:flex-row">
          {/* Sidebar */}
          <div className="flex-shrink-0 md:w-64 print:hidden">
            <div className="md:sticky md:top-8">
              <TableOfContents items={tocItems} />
            </div>
          </div>

          {/* Content */}
          <div className="min-w-0 flex-1 max-w-3xl">
            <div className="prose prose-slate max-w-none prose-headings:font-serif prose-headings:font-semibold prose-headings:tracking-tight prose-p:text-slate-700 prose-p:leading-relaxed prose-p:text-base prose-a:text-[#15406a] prose-ul:space-y-2 prose-li:marker:text-slate-500 print:prose-p:text-black print:prose-headings:text-black print:prose-a:text-black print:prose-strong:text-black">

              <p className="lead text-slate-600 text-lg">
                This Privacy Policy (the <strong>&quot;Policy&quot;</strong>) governs the collection, processing, storage, and protection of personal and corporate data submitted to or generated by the Tender Management System (the <strong>&quot;TMS&quot;</strong>), operated by Beauty One International Pte Ltd. (<strong>&quot;we,&quot;</strong> <strong>&quot;our,&quot;</strong> or <strong>&quot;us&quot;</strong>). We are committed to protecting the privacy and security of all data processed through the TMS, in compliance with the Singapore Personal Data Protection Act (<strong>PDPA</strong>).
              </p>

              <p className="mt-6">This Policy applies to all users of the TMS, including:</p>
              <LegalList
                items={[
                  <span key="1">
                    <strong>Internal Team Members:</strong> Employees, contractors, and authorised personnel who access the TMS for project governance, tender management, and operational oversight.
                  </span>,
                  <span key="2">
                    <strong>External Contractors:</strong> Third‑party contracting firms, vendors, and personnel who submit tender bids, commercial proposals, and compliance documentation through the TMS.
                  </span>,
                ]}
              />

              <SectionHeader id="section1" level={2}>1. Categories of Collected Information</SectionHeader>
              <p>The TMS collects and processes information across four principal categories, with strict data segmentation to preserve commercial confidentiality. We collect only what is necessary for procurement, project governance, and compliance.</p>

              <SectionHeader level={3}>1.1 Corporate &amp; Compliance Data</SectionHeader>
              <LegalList
                items={[
                  <span key="1-1"><strong>Company Registration:</strong> Business registration numbers, certificates of incorporation, UEN/tax identification numbers</span>,
                  <span key="1-2"><strong>Financial Standing:</strong> Audited financial statements, bank confirmation letters, credit references, proof of insurance coverage</span>,
                  <span key="1-3"><strong>Compliance Credentials:</strong> Industry accreditations, safety compliance documentation, professional licenses</span>,
                  <span key="1-4"><strong>Performance Metrics:</strong> Historical project completion records, quality assessment scores, on‑time delivery tracking</span>,
                  <span key="1-5"><strong>Audit Records:</strong> Financial transactions, approval workflows, and compliance verification events</span>,
                ]}
              />

              <SectionHeader level={3}>1.2 Personnel &amp; Contact Data</SectionHeader>
              <LegalList
                items={[
                  <span key="2-1"><strong>Direct Identifiers:</strong> Full name, official job title, corporate email address, direct telephone numbers</span>,
                  <span key="2-2"><strong>Role‑Based Attributes:</strong> Employment status, departmental assignment, authority/approval rights within the TMS</span>,
                  <span key="2-3"><strong>Professional History:</strong> Curriculum vitae summaries, professional certifications, skills profiles (where submitted voluntarily)</span>,
                  <span key="2-4"><strong>User Credentials:</strong> System login credentials (securely hashed, never stored in plain text), access role assignments</span>,
                ]}
              />

              <SectionHeader level={3}>1.3 Commercial &amp; Pricing Data</SectionHeader>
              <LegalList
                items={[
                  <span key="3-1"><strong>Bill of Quantities (BQ):</strong> Detailed itemised breakdowns of materials, labour, equipment, and cost components</span>,
                  <span key="3-2"><strong>Line‑Item Pricing:</strong> Unit rates, extended totals, discount structures applied to bid proposals</span>,
                  <span key="3-3"><strong>Bidding Histories:</strong> Historical records of tender submissions, outcomes (awarded, declined, withdrawn), contract values</span>,
                  <span key="3-4"><strong>Contractual Documentation:</strong> Signed contracts, variation orders, amendment records, scope‑of‑work deliverables</span>,
                  <span key="3-5"><strong>Estimated Budget Data:</strong> Internal cost projections, budget ceilings, financial benchmarking data for evaluation</span>,
                ]}
              />

              <SectionHeader level={3}>1.4 Technical Logs &amp; System Telemetry</SectionHeader>
              <LegalList
                items={[
                  <span key="4-1"><strong>Access Logs:</strong> Records of authentication attempts, session duration, logout times</span>,
                  <span key="4-2"><strong>Interaction Logs:</strong> Feature usage, document uploads/edits, navigation patterns</span>,
                  <span key="4-3"><strong>Device Identifiers:</strong> IP addresses, browser type and version, operating system details, device fingerprints</span>,
                  <span key="4-4"><strong>Audit Trails:</strong> Immutable records of all data changes—who accessed, modified, or approved data elements</span>,
                  <span key="4-5"><strong>System Performance:</strong> API call logs, error logs, system response metrics</span>,
                ]}
              />
              <p className="text-sm text-slate-500">We collect only data strictly necessary for the purposes described in Section 2, in accordance with data minimisation principles under the PDPA.</p>

              <SectionHeader id="section2" level={2}>2. Purpose and Lawful Basis of Processing</SectionHeader>
              <p>All processing activities are conducted for legitimate purposes and in accordance with the PDPA.</p>

              <SectionHeader level={3}>2.1 Purposes of Processing</SectionHeader>
              <LegalList
                variant="decimal"
                items={[
                  <span key="p1">
                    <strong>Contractual &amp; Pre‑Contractual Obligations</strong>
                    <LegalList
                      items={[
                        <span key="p1-1">Facilitate contractor registration and tender submission</span>,
                        <span key="p1-2">Evaluate tenders against pre‑defined criteria (cost, capability, compliance)</span>,
                        <span key="p1-3">Communicate tender outcomes to participating parties</span>,
                        <span key="p1-4">Administer awarded contracts, including project governance and milestone tracking</span>,
                      ]}
                    />
                  </span>,
                  <span key="p2">
                    <strong>Project Governance &amp; Cost Optimisation</strong>
                    <LegalList
                      items={[
                        <span key="p2-1">Cost variance analysis and budget tracking</span>,
                        <span key="p2-2">Risk identification and mitigation</span>,
                        <span key="p2-3">Performance benchmarking and continuous improvement</span>,
                        <span key="p2-4">Audit‑ready financial reporting</span>,
                      ]}
                    />
                  </span>,
                  <span key="p3">
                    <strong>System Security &amp; Fraud Prevention</strong>
                    <LegalList
                      items={[
                        <span key="p3-1">Corporate verification and identity authentication</span>,
                        <span key="p3-2">Anomaly detection and suspicious activity monitoring</span>,
                        <span key="p3-3">Access control enforcement</span>,
                        <span key="p3-4">Security incident investigation and response</span>,
                      ]}
                    />
                  </span>,
                  <span key="p4">
                    <strong>Legal &amp; Regulatory Compliance</strong>
                    <LegalList
                      items={[
                        <span key="p4-1">Retention of financial records for tax and statutory audit requirements</span>,
                        <span key="p4-2">Compliance with requests from regulatory authorities or law enforcement</span>,
                        <span key="p4-3">Adherence to industry‑specific reporting obligations</span>,
                      ]}
                    />
                  </span>,
                ]}
              />

              <SectionHeader level={3}>2.2 Lawful Bases under PDPA</SectionHeader>
              <p>Under the PDPA, our processing is based on the following lawful grounds:</p>
              <LegalList
                items={[
                  <span key="lb1"><strong>Consent:</strong> Where you have provided clear consent for specific processing activities.</span>,
                  <span key="lb2"><strong>Contractual Necessity:</strong> Processing necessary to perform a contract with you or to take pre‑contractual steps at your request.</span>,
                  <span key="lb3"><strong>Legal Obligation:</strong> Processing required to comply with a legal obligation (e.g., tax, audit, regulatory reporting).</span>,
                  <span key="lb4"><strong>Legitimate Interests:</strong> Processing necessary for our legitimate business interests (system security, fraud prevention, service improvement) that does not override your rights and freedoms. We have assessed that this processing is necessary, proportionate, and does not prejudice your rights.</span>,
                ]}
              />

              <SectionHeader id="section3" level={2}>3. Data Sharing, Retention &amp; Access Governance</SectionHeader>

              <SectionHeader level={3}>3.1 Data Sharing — Confidentiality &amp; Siloing</SectionHeader>
              <p>We maintain strict data siloing and confidentiality protocols. We do not sell, rent, or trade personal data to third parties for marketing purposes. Bid pricing, commercial proposals, and BQ data are strictly segregated and never shared with competing contractors. Evaluation scores and award recommendations are accessible only to authorised internal evaluators, and access to any data category is granted strictly on a need‑to‑know basis.</p>
              <p><strong>Permitted disclosures</strong> are limited to:</p>
              <LegalList
                items={[
                  <span key="3-1-5"><strong>Internal Access:</strong> Authorised personnel granted access strictly on a need‑to‑know basis.</span>,
                  <span key="3-1-6"><strong>Service Providers:</strong> Third‑party providers (cloud hosting, security monitoring) bound by strict data processing agreements (DPAs).</span>,
                  <span key="3-1-7"><strong>Regulatory Authorities:</strong> Where required by applicable law or valid legal request.</span>,
                  <span key="3-1-8"><strong>Successor Entities:</strong> In the event of merger, acquisition, or corporate restructuring, subject to continued compliance with this Policy.</span>,
                ]}
              />

              <SectionHeader level={3}>3.2 Data Retention Parameters</SectionHeader>
              <div className="overflow-x-auto my-6">
                <table className="min-w-full text-sm border border-slate-200">
                  <thead className="bg-slate-50">
                    <tr>
                      <th className="px-5 py-3 text-left font-semibold">Data Category</th>
                      <th className="px-5 py-3 text-left font-semibold">Retention Period</th>
                      <th className="px-5 py-3 text-left font-semibold">Rationale</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="border-t border-slate-200"><td className="px-5 py-3">Financial Audit Records</td><td className="px-5 py-3">7 years from end of financial year</td><td className="px-5 py-3">Statutory audit and regulatory compliance</td></tr>
                    <tr className="border-t border-slate-200 bg-slate-50/50"><td className="px-5 py-3">Commercial &amp; Pricing Data</td><td className="px-5 py-3">7 years</td><td className="px-5 py-3">Tax and financial audit compliance</td></tr>
                    <tr className="border-t border-slate-200"><td className="px-5 py-3">Contractual Documents</td><td className="px-5 py-3">7 years from contract expiry/termination</td><td className="px-5 py-3">Legal claims limitation periods</td></tr>
                    <tr className="border-t border-slate-200 bg-slate-50/50"><td className="px-5 py-3">Bidder Portfolios</td><td className="px-5 py-3">5 years</td><td className="px-5 py-3">Maintain historical contractor profiles for future procurement cycles</td></tr>
                    <tr className="border-t border-slate-200"><td className="px-5 py-3">Active Tender Records</td><td className="px-5 py-3">Duration of tender process + 3 years</td><td className="px-5 py-3">Facilitate post‑tender queries, audits, historical reference</td></tr>
                    <tr className="border-t border-slate-200 bg-slate-50/50"><td className="px-5 py-3">Access &amp; Technical Logs</td><td className="px-5 py-3">2 years</td><td className="px-5 py-3">Security monitoring, incident investigation, forensic analysis</td></tr>
                    <tr className="border-t border-slate-200"><td className="px-5 py-3">Declined Tender Data</td><td className="px-5 py-3">2 years (post‑closing)</td><td className="px-5 py-3">Permit fair challenge processes and historical analysis</td></tr>
                  </tbody>
                </table>
              </div>
              <p>Data may be retained longer if required to establish, exercise, or defend a legal claim, or where mandated by applicable law. Beyond its retention period, data is securely deleted from production systems, anonymised for analytical purposes where beneficial, or archived in encrypted, access‑controlled storage for legal hold purposes.</p>

              <SectionHeader level={3}>3.3 Access Governance</SectionHeader>
              <LegalList
                items={[
                  <span key="3-3-1"><strong>Role‑Based Access Control (RBAC):</strong> Access rights granted based on job function and data classification.</span>,
                  <span key="3-3-2"><strong>Principle of Least Privilege:</strong> Users granted minimum access necessary to perform duties.</span>,
                  <span key="3-3-3"><strong>Segregation of Duties:</strong> Conflicting roles (e.g., bid evaluation and contract award) assigned to different individuals.</span>,
                  <span key="3-3-4"><strong>Access Review:</strong> Quarterly reviews ensure continued appropriateness of permissions.</span>,
                  <span key="3-3-5"><strong>Access Logging:</strong> All data access events logged and retained for audit purposes.</span>,
                  <span key="3-3-6"><strong>Sensitive Financial Blocks:</strong> Commercial pricing stored in isolated logical partitions with restricted access.</span>,
                ]}
              />

              <SectionHeader id="section4" level={2}>4. Data Security &amp; Enterprise Safeguards</SectionHeader>
              <p>We implement industry‑standard technical and organisational measures to protect data against unauthorised access, loss, destruction, or alteration.</p>

              <SectionHeader level={3}>4.1 Encryption Standards</SectionHeader>
              <LegalList
                items={[
                  <span key="4-1-1"><strong>Data in Transit:</strong> Database connections and all data transmitted between client devices and our servers are encrypted in transit (TLS), with certificate verification enforced in production.</span>,
                  <span key="4-1-2"><strong>Sensitive Fields at Rest:</strong> Select highly sensitive fields are encrypted at the application layer using AES‑256‑GCM before storage. Broader database and disk‑level encryption depends on our hosting infrastructure.</span>,
                ]}
              />

              <SectionHeader level={3}>4.2 Access Controls</SectionHeader>
              <LegalList
                items={[
                  <span key="4-2-1"><strong>Role‑Based Access Control (RBAC):</strong> Every user is assigned one or more roles, and access to each feature and data category is enforced per‑request based on those roles.</span>,
                  <span key="4-2-2"><strong>Session Management:</strong> Sessions expire automatically after a period of inactivity, requiring re‑authentication.</span>,
                  <span key="4-2-3"><strong>Password Policy:</strong> Enforced password complexity requirements; accounts are temporarily locked after repeated failed login attempts.</span>,
                  <span key="4-2-4"><strong>Login Monitoring:</strong> Login attempts (successful and failed) are recorded with IP address and device information, and account holders are alerted by email of new logins.</span>,
                ]}
              />

              <SectionHeader level={3}>4.3 Data Segregation &amp; Isolation</SectionHeader>
              <LegalList
                items={[
                  <span key="4-3-1"><strong>Tenant Isolation:</strong> Logical separation of data belonging to different clients and contractors.</span>,
                  <span key="4-3-2"><strong>Sensitive Data Redaction:</strong> Automatic redaction of sensitive financial data in non‑production environments.</span>,
                  <span key="4-3-3"><strong>Staging Controls:</strong> Production data never used in development/testing without appropriate anonymisation.</span>,
                ]}
              />

              <SectionHeader level={3}>4.4 Monitoring &amp; Incident Response</SectionHeader>
              <LegalList
                items={[
                  <span key="4-4-1"><strong>Audit Logging:</strong> Comprehensive audit trails of all data access, modification, and deletion events.</span>,
                  <span key="4-4-2"><strong>Incident Response Plan:</strong> Documented and tested procedures for data breach scenarios.</span>,
                  <span key="4-4-3"><strong>Breach Notification:</strong> Affected data subjects and the Personal Data Protection Commission (PDPC) notified promptly in the event of a notifiable breach.</span>,
                ]}
              />

              <SectionHeader level={3}>4.5 Organisational Measures</SectionHeader>
              <LegalList
                items={[
                  <span key="4-5-1"><strong>Data Protection Officer (DPO):</strong> Appointed to ensure compliance with the PDPA.</span>,
                  <span key="4-5-2"><strong>Staff Training:</strong> Mandatory data privacy and security training on induction and annually.</span>,
                  <span key="4-5-3"><strong>Vendor Due Diligence:</strong> All third‑party providers subject to security and privacy assessments.</span>,
                  <span key="4-5-4"><strong>Data Protection by Design:</strong> Privacy and security integrated into all system development processes.</span>,
                  <span key="4-5-5"><strong>Business Continuity:</strong> Regular database backups are maintained to support recovery in the event of data loss.</span>,
                ]}
              />

              <SectionHeader id="section5" level={2}>5. Your Privacy Rights</SectionHeader>

              <SectionHeader level={3}>5.1 Your Rights under PDPA</SectionHeader>
              <p>Under the Personal Data Protection Act (PDPA) of Singapore, you have the following rights:</p>
              <LegalList
                items={[
                  <span key="5-1-1"><strong>Right of Access:</strong> Request a copy of the personal data we hold about you.</span>,
                  <span key="5-1-2"><strong>Right to Correction:</strong> Request correction of inaccurate or incomplete data.</span>,
                  <span key="5-1-3"><strong>Right to Withdraw Consent:</strong> Withdraw consent for processing at any time (subject to legal/contractual restrictions).</span>,
                  <span key="5-1-4"><strong>Right to Data Portability:</strong> Request transfer of your data in a machine‑readable format (where applicable).</span>,
                  <span key="5-1-5"><strong>Right to Lodge a Complaint:</strong> Lodge a complaint with the Personal Data Protection Commission (PDPC).</span>,
                ]}
              />

              <SectionHeader level={3}>5.2 How to Exercise Your Rights</SectionHeader>
              <p>To exercise any data subject right, please contact our Data Protection Officer using the details in Section 6. All requests are acknowledged within seven (7) business days, substantively responded to within thirty (30) days (or sooner if required by law), and provided free of charge unless manifestly unfounded or excessive.</p>

              <SectionHeader id="section6" level={2}>6. Data Protection Officer &amp; Contact Information</SectionHeader>
              <p>
                <strong>Data Protection Officer</strong><br />
                Beauty One International Pte Ltd.<br />
                2 Venture Drive, #21‑01, VISION EXCHANGE, Singapore 608526<br />
                <strong>Email:</strong> dpo@beautyone.com.sg<br />
                <strong>For data subject requests:</strong> tender_enquiries@beautyone.com.sg
              </p>

              <SectionHeader id="section7" level={2}>7. Cookies &amp; Tracking Technologies</SectionHeader>
              <p>The TMS uses only strictly necessary cookies — session authentication and security (e.g., CSRF protection). We do not use analytics, advertising, or third‑party tracking cookies. You can manage or block cookies through your browser settings, though because the TMS uses only essential cookies, disabling them will prevent you from logging in or using the TMS.</p>

              <SectionHeader id="section8" level={2}>8. Data Storage Location</SectionHeader>
              <p>Your data is stored and processed within Singapore. We do not transfer your data outside Singapore for storage or processing. In the limited event that a service provider engaged to support the TMS (e.g., for security monitoring) is located outside Singapore, any such transfer will comply with the PDPA through appropriate safeguards, such as standard contractual clauses approved by the PDPC or equivalent legally recognised transfer mechanisms.</p>

              <SectionHeader id="section9" level={2}>9. Children&apos;s Privacy</SectionHeader>
              <p>The TMS is not intended for children under the age of 16. We do not knowingly collect personal information from children. If we become aware of such collection without verifiable parental consent, we will delete that data.</p>

              <SectionHeader id="section10" level={2}>10. Policy Updates &amp; Notification</SectionHeader>
              <p>This Policy is reviewed annually, or as required by changes in law or operational practice. Material changes will be communicated by email to registered users, an in‑app notification, and publication of the updated Policy with its revision date clearly indicated. Continued use of the TMS after the effective date shown above constitutes acceptance of the updated Policy.</p>

              <SectionHeader id="section11" level={2}>11. Compliance &amp; Accountability</SectionHeader>
              <LegalList
                items={[
                  <span key="11-1"><strong>Data Protection Impact Assessments (DPIAs):</strong> Conducted for new processing activities that present a high risk to rights and freedoms of data subjects.</span>,
                  <span key="11-2"><strong>Record of Processing Activities (ROPA):</strong> We maintain a detailed ROPA as required by the PDPA.</span>,
                  <span key="11-3"><strong>Employee Training:</strong> All personnel with TMS access receive mandatory data privacy and security training on induction and annually thereafter.</span>,
                  <span key="11-4"><strong>Regulatory Cooperation:</strong> We cooperate fully with the Personal Data Protection Commission (PDPC) in the exercise of its regulatory powers.</span>,
                ]}
              />

              <SectionHeader id="appendix" level={2}>Appendix A: Definitions</SectionHeader>
              <div className="overflow-x-auto my-6">
                <table className="min-w-full text-sm border border-slate-200">
                  <thead className="bg-slate-50">
                    <tr><th className="px-5 py-3 text-left font-semibold">Term</th><th className="px-5 py-3 text-left font-semibold">Definition</th></tr>
                  </thead>
                  <tbody>
                    <tr className="border-t border-slate-200"><td className="px-5 py-3">BQ</td><td className="px-5 py-3">Bill of Quantities — detailed itemised breakdown of costs submitted as part of a tender proposal.</td></tr>
                    <tr className="border-t border-slate-200 bg-slate-50/50"><td className="px-5 py-3">Data Controller</td><td className="px-5 py-3">The entity that determines purposes and means of processing personal data (Beauty One International Pte Ltd.).</td></tr>
                    <tr className="border-t border-slate-200"><td className="px-5 py-3">Data Processor</td><td className="px-5 py-3">The entity that processes personal data on behalf of the Data Controller (service providers).</td></tr>
                    <tr className="border-t border-slate-200 bg-slate-50/50"><td className="px-5 py-3">Data Subject</td><td className="px-5 py-3">An identified or identifiable natural person whose personal data is processed.</td></tr>
                    <tr className="border-t border-slate-200"><td className="px-5 py-3">DPA</td><td className="px-5 py-3">Data Processing Agreement — binding contract between Controller and Processor.</td></tr>
                    <tr className="border-t border-slate-200 bg-slate-50/50"><td className="px-5 py-3">DPO</td><td className="px-5 py-3">Data Protection Officer — individual designated to oversee data protection compliance.</td></tr>
                    <tr className="border-t border-slate-200"><td className="px-5 py-3">PDPA</td><td className="px-5 py-3">Personal Data Protection Act (Singapore).</td></tr>
                    <tr className="border-t border-slate-200 bg-slate-50/50"><td className="px-5 py-3">RBAC</td><td className="px-5 py-3">Role‑Based Access Control — system that restricts access based on user&apos;s role.</td></tr>
                    <tr className="border-t border-slate-200"><td className="px-5 py-3">ROPA</td><td className="px-5 py-3">Record of Processing Activities — register of all processing activities.</td></tr>
                    <tr className="border-t border-slate-200 bg-slate-50/50"><td className="px-5 py-3">Sensitive Data</td><td className="px-5 py-3">Data requiring higher protection: financial records, commercial pricing, compliance documentation.</td></tr>
                    <tr className="border-t border-slate-200"><td className="px-5 py-3">Supervisory Authority</td><td className="px-5 py-3">The Personal Data Protection Commission (PDPC) of Singapore.</td></tr>
                    <tr className="border-t border-slate-200 bg-slate-50/50"><td className="px-5 py-3">TMS</td><td className="px-5 py-3">The Tender Management System, including all associated software and services.</td></tr>
                  </tbody>
                </table>
              </div>

              <p className="mt-14 text-xs text-slate-400 border-t border-slate-200 pt-6">
                This Privacy Policy is provided for informational purposes and does not constitute legal advice. Copyright © 2026 Beauty One International Pte Ltd. All rights reserved.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
