// app/api/bq/items/route.ts
import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { query } from "@/lib/db";
import { canEditLineItem } from "@/lib/permissions";
import { bqLineItemCreateSchema, bqLineItemUpdateSchema } from "@/lib/validation";

async function getNextSortOrder(
  submissionId: number,
  categoryId: number,
  parentId: number | null
): Promise<number> {
  const res = await query(
    `SELECT COALESCE(MAX(sort_order), 0) + 1 AS next_sort
     FROM bq_line_item
     WHERE submission_id = $1 AND category_id = $2 AND parent_item_id IS NOT DISTINCT FROM $3`,
    [submissionId, categoryId, parentId]
  );
  return res.rows[0].next_sort;
}

async function getLevel(parentId: number | null): Promise<number> {
  if (!parentId) return 0;
  const res = await query(`SELECT level FROM bq_line_item WHERE line_item_id = $1`, [parentId]);
  return res.rows.length ? res.rows[0].level + 1 : 0;
}

export async function POST(req: Request) {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  // Parse JSON body manually
  let body;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  // Validate with Zod
  const validation = bqLineItemCreateSchema.safeParse(body);
  if (!validation.success) {
    return NextResponse.json({ error: validation.error.message }, { status: 400 });
  }
  const data = validation.data;

  // Permission check – pass role_id as array if your function expects it, or single value
  const canEdit = await canEditLineItem(0, session.user.id, [session.user.role_id], data.submission_id);
  if (!canEdit) {
    return NextResponse.json({ error: "Forbidden – you cannot add items to this BQ" }, { status: 403 });
  }

  const level = await getLevel(data.parent_item_id || null);
  const sort_order = await getNextSortOrder(data.submission_id, data.category_id, data.parent_item_id || null);

  // Insert – DO NOT include amount; it's generated by the database (GENERATED ALWAYS)
  const result = await query(
    `INSERT INTO bq_line_item
      (submission_id, category_id, parent_item_id,
       location, description, specifications, brand,
       quantity, unit, unit_price, discount,
       sort_order, level)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
     RETURNING line_item_id`,
    [
      data.submission_id,
      data.category_id,
      data.parent_item_id || null,
      data.location || "",
      data.description || "",
      data.specifications || "",
      data.brand || "",
      data.quantity,
      data.unit,
      data.unit_price,
      data.discount || 0,
      sort_order,
      level,
    ]
  );

  return NextResponse.json({ line_item_id: result.rows[0].line_item_id });
}

export async function PUT(req: Request) {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  let body;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const validation = bqLineItemUpdateSchema.safeParse(body);
  if (!validation.success) {
    return NextResponse.json({ error: validation.error.message }, { status: 400 });
  }
  const { line_item_id, ...fields } = validation.data;

  // Permission check
  const canEdit = await canEditLineItem(line_item_id, session.user.id, [session.user.role_id]);
  if (!canEdit) {
    return NextResponse.json({ error: "Forbidden – you cannot edit this item" }, { status: 403 });
  }

  // Remove fields that should not be updated directly
  delete (fields as any).amount;
  delete (fields as any).line_item_id;
  delete (fields as any).created_at;

  const entries = Object.entries(fields).filter(([, v]) => v !== undefined);
  if (entries.length === 0) {
    return NextResponse.json({ error: "No fields to update" }, { status: 400 });
  }

  let needRecalc = entries.some(([key]) => ["quantity", "unit_price", "discount"].includes(key));
  let setClause = entries.map(([key], i) => `${key} = $${i + 2}`).join(", ");
  const values = [line_item_id, ...entries.map(([, v]) => v)];

  // If quantity, unit_price, or discount changed, the DB will recompute amount automatically,
  // but we don't need to update it manually – the column is GENERATED ALWAYS.
  // We only need to trigger the update; the DB handles the rest.

  await query(`UPDATE bq_line_item SET ${setClause}, updated_at = NOW() WHERE line_item_id = $1`, values);
  return NextResponse.json({ success: true });
}

export async function DELETE(req: Request) {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  let body;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const { line_item_id } = body;
  if (!line_item_id) {
    return NextResponse.json({ error: "Missing line_item_id" }, { status: 400 });
  }

  const canEdit = await canEditLineItem(line_item_id, session.user.id, [session.user.role_id]);
  if (!canEdit) {
    return NextResponse.json({ error: "Forbidden – you cannot delete this item" }, { status: 403 });
  }

  await query(`DELETE FROM bq_line_item WHERE line_item_id = $1`, [line_item_id]);
  return NextResponse.json({ success: true });
}